name: Azure Function Deploy With CICD.
on:
  push:
    branches:
      - main

permissions:
      id-token: write
      contents: read
jobs: 
  deploy-functions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
          architecture: x64

      - name: Install required python modules
        run: |
            cd ./AzureFunctionDeploy
            python -m pip install --upgrade pip
            pip install --target="./.python_packages/lib/site-packages" -r requirements.txt 

      - name: Zip the Azure Function Deploy folder
        run: |
          cd AzureFunctionDeploy
          zip -r ../AzureFunctionDeploy.zip ./*

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: 246cfd43-77c5-4c63-8f77-d6a19a3876ec
          tenant-id: e4e34038-ea1f-4882-b6e8-ccd776459ca0
          subscription-id: 737d1672-96a9-4ba4-b12c-8027ef27ab4e
  
      - name: 'Run az commands'
        run: |
          az account show
          az group list

      - name: 'Build and Deploy to Azure'
        run: |
          az functionapp deployment source config-zip \
          --resource-group "costoptimizationsas" \
          --name "testfunccloud" \
          --src "./AzureFunctionDeploy.zip"
